LINKS = -lglut -lGLU -lGL -lm 
INCS = -I. -I ../../include
CC = gcc
SRCS    = .

EXEC = Window
PROG:	Window \

FILES =	
Window:	Window.c
	$(CC)	$@.c 	$(INCS)	$(LDPATH) $(LINKS)	-o $@

clean:
	 rm  $(EXEC)
